[tool.poetry]
name = "discotoken"
version = "0.1.0"
description = ""
authors = ["LEANDROTN"]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
